export const NEPALI_COURTS = [
  'Supreme Court of Nepal',
  'High Court Biratnagar',
  'High Court Janakpur',
  'High Court Patan',
  'High Court Pokhara',
  'High Court Tulsipur',
  'High Court Surkhet',
  'High Court Dipayal',
  'Kathmandu District Court',
  'Lalitpur District Court',
  'Bhaktapur District Court',
  'Special Court',
  'Labor Court',
  'Revenue Tribunal',
  'Debt Recovery Tribunal',
  'Foreign Employment Tribunal',
  'Administrative Court',
]
